"""email_verified column added

Revision ID: 773556a6fdd8
Revises: 
Create Date: 2024-11-27 15:11:01.248135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773556a6fdd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
